---
getQuest: '§eNom de la tâche: §c§l> §e {quest}'
getQuestInfo: '§aQuest: §f {type} §a {count} §2 {target}'
questEnded: '§aVous avez terminé toutes les tâches du serveur! Toutes nos félicitations!'
questNotExist: '§a La tâche n''existe pas. Utilisez la commande §e/quest §avoir la liste des tâches. '
questHelp: '§a nom de la mission: §c§l> §r§e {quest} La tâche que vous devez faire: §f {type} {count} §2 {target} '
questEnd: '§a Achevée! Ta récompense: §b {count} {award} §a! '

# all quests can have
# blockBreak
# blockPlace
# If you need blockBreak or blockPlace - Write it all
# playerKill
# playerDeath
# itemConsume
# itemDrop
# jump
quests:
  - name: First Mission
    task: blockBreak
    target: stone block
    id: 1
    num: 10
    award:
      id: money
      count: 1000
      name: coins
  - name: Second Mission
    task: blockPlace
    target: stone block
    id: 1
    num: 10
    award:
      id: money
      count: 1000
      name: coins
  - name: Third Mission
    task: itemDrop
    target: block diamonds
    id: 57
    num: 10
    award:
      id: money
      count: 1000
      name: coins
  - name: Mission Four
    task: itemConsume
    target: golden apple
    id: 322
    num: 2
    award:
      id: money
      count: 1000
      name: coins
  - name: Mission Five
    task: jump
    target: 10
    award:
      id: money
      count: 1000
      name: coins
...